require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InodesController do

  # This should return the minimal set of attributes required to create a valid
  # Inode. As you add validations to Inode, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "shasum" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InodesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all inodes as @inodes" do
      inode = Inode.create! valid_attributes
      get :index, {}, valid_session
      assigns(:inodes).should eq([inode])
    end
  end

  describe "GET show" do
    it "assigns the requested inode as @inode" do
      inode = Inode.create! valid_attributes
      get :show, {:id => inode.to_param}, valid_session
      assigns(:inode).should eq(inode)
    end
  end

  describe "GET new" do
    it "assigns a new inode as @inode" do
      get :new, {}, valid_session
      assigns(:inode).should be_a_new(Inode)
    end
  end

  describe "GET edit" do
    it "assigns the requested inode as @inode" do
      inode = Inode.create! valid_attributes
      get :edit, {:id => inode.to_param}, valid_session
      assigns(:inode).should eq(inode)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Inode" do
        expect {
          post :create, {:inode => valid_attributes}, valid_session
        }.to change(Inode, :count).by(1)
      end

      it "assigns a newly created inode as @inode" do
        post :create, {:inode => valid_attributes}, valid_session
        assigns(:inode).should be_a(Inode)
        assigns(:inode).should be_persisted
      end

      it "redirects to the created inode" do
        post :create, {:inode => valid_attributes}, valid_session
        response.should redirect_to(Inode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved inode as @inode" do
        # Trigger the behavior that occurs when invalid params are submitted
        Inode.any_instance.stub(:save).and_return(false)
        post :create, {:inode => { "shasum" => "invalid value" }}, valid_session
        assigns(:inode).should be_a_new(Inode)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Inode.any_instance.stub(:save).and_return(false)
        post :create, {:inode => { "shasum" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested inode" do
        inode = Inode.create! valid_attributes
        # Assuming there are no other inodes in the database, this
        # specifies that the Inode created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Inode.any_instance.should_receive(:update).with({ "shasum" => "MyString" })
        put :update, {:id => inode.to_param, :inode => { "shasum" => "MyString" }}, valid_session
      end

      it "assigns the requested inode as @inode" do
        inode = Inode.create! valid_attributes
        put :update, {:id => inode.to_param, :inode => valid_attributes}, valid_session
        assigns(:inode).should eq(inode)
      end

      it "redirects to the inode" do
        inode = Inode.create! valid_attributes
        put :update, {:id => inode.to_param, :inode => valid_attributes}, valid_session
        response.should redirect_to(inode)
      end
    end

    describe "with invalid params" do
      it "assigns the inode as @inode" do
        inode = Inode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Inode.any_instance.stub(:save).and_return(false)
        put :update, {:id => inode.to_param, :inode => { "shasum" => "invalid value" }}, valid_session
        assigns(:inode).should eq(inode)
      end

      it "re-renders the 'edit' template" do
        inode = Inode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Inode.any_instance.stub(:save).and_return(false)
        put :update, {:id => inode.to_param, :inode => { "shasum" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested inode" do
      inode = Inode.create! valid_attributes
      expect {
        delete :destroy, {:id => inode.to_param}, valid_session
      }.to change(Inode, :count).by(-1)
    end

    it "redirects to the inodes list" do
      inode = Inode.create! valid_attributes
      delete :destroy, {:id => inode.to_param}, valid_session
      response.should redirect_to(inodes_url)
    end
  end

end
